# Dependencies
highlighter:      rouge

# Config
gems: [jekyll-gist,jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            "Danielle's Detours"
tagline:          'Summer quarter 2016'
description:      'Adventures in the world of data journalism'

<iframe width="560" height="315" src="https://www.youtube.com/embed/iDbyYGrswtg" frameborder="0" allowfullscreen></iframe>
url:              http://digitalframeworks.github.io
baseurl:          /

author:
  name:           'Danielle Prieur'
  url:            https://twitter.com/eads

paginate:         15

exclude: [node_modules]

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
navlinks:
- url: https://nwudigitalframeworks.slack.com/messages/general/
  title: Slack
- url: mailto:davideads@gmail.com
  title: Email
